<?php

use Illuminate\Database\Seeder;
use App\Models\Municipio;
use Carbon\Carbon as DateTime;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){

        $municipios = [
			['id' => 1, 'id_estado' => 1, 'municipio' => "Alto Orinoco", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 2, 'id_estado' => 1, 'municipio' => "Atabapo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 3, 'id_estado' => 1, 'municipio' => "Atures", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 4, 'id_estado' => 1, 'municipio' => "Autana", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 5, 'id_estado' => 1, 'municipio' => "Manapiare", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 6, 'id_estado' => 1, 'municipio' => "Maroa", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 7, 'id_estado' => 1, 'municipio' => "Río Negro", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 8, 'id_estado' => 2, 'municipio' => "Anaco", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 9, 'id_estado' => 2, 'municipio' => "Aragua", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 10, 'id_estado' => 2, 'municipio' => "Manuel Ezequiel Bruzual", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 11, 'id_estado' => 2, 'municipio' => "Diego Bautista Urbaneja", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 12, 'id_estado' => 2, 'municipio' => "Fernando Peñalver", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 13, 'id_estado' => 2, 'municipio' => "Francisco Del Carmen Carvajal", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 14, 'id_estado' => 2, 'municipio' => "General Sir Arthur McGregor", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 15, 'id_estado' => 2, 'municipio' => "Guanta", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 16, 'id_estado' => 2, 'municipio' => "Independencia", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 17, 'id_estado' => 2, 'municipio' => "José Gregorio Monagas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 18, 'id_estado' => 2, 'municipio' => "Juan Antonio Sotillo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 19, 'id_estado' => 2, 'municipio' => "Juan Manuel Cajigal", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 20, 'id_estado' => 2, 'municipio' => "Libertad", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 21, 'id_estado' => 2, 'municipio' => "Francisco de Miranda", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 22, 'id_estado' => 2, 'municipio' => "Pedro María Freites", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 23, 'id_estado' => 2, 'municipio' => "Píritu", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 24, 'id_estado' => 2, 'municipio' => "San José de Guanipa", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 25, 'id_estado' => 2, 'municipio' => "San Juan de Capistrano", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 26, 'id_estado' => 2, 'municipio' => "Santa Ana", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 27, 'id_estado' => 2, 'municipio' => "Simón Bolívar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 28, 'id_estado' => 2, 'municipio' => "Simón Rodríguez", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 29, 'id_estado' => 3, 'municipio' => "Achaguas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 30, 'id_estado' => 3, 'municipio' => "Biruaca", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 31, 'id_estado' => 3, 'municipio' => "Muñóz", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 32, 'id_estado' => 3, 'municipio' => "Páez", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 33, 'id_estado' => 3, 'municipio' => "Pedro Camejo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 34, 'id_estado' => 3, 'municipio' => "Rómulo Gallegos", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 35, 'id_estado' => 3, 'municipio' => "San Fernando", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 36, 'id_estado' => 4, 'municipio' => "Atanasio Girardot", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 37, 'id_estado' => 4, 'municipio' => "Bolívar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 38, 'id_estado' => 4, 'municipio' => "Camatagua", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 39, 'id_estado' => 4, 'municipio' => "Francisco Linares Alcántara", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 40, 'id_estado' => 4, 'municipio' => "José Ángel Lamas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 41, 'id_estado' => 4, 'municipio' => "José Félix Ribas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 42, 'id_estado' => 4, 'municipio' => "José Rafael Revenga", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 43, 'id_estado' => 4, 'municipio' => "Libertador", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 44, 'id_estado' => 4, 'municipio' => "Mario Briceño Iragorry", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 45, 'id_estado' => 4, 'municipio' => "Ocumare de la Costa de Oro", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 46, 'id_estado' => 4, 'municipio' => "San Casimiro", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 47, 'id_estado' => 4, 'municipio' => "San Sebastián", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 48, 'id_estado' => 4, 'municipio' => "Santiago Mariño", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 49, 'id_estado' => 4, 'municipio' => "Santos Michelena", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 50, 'id_estado' => 4, 'municipio' => "Sucre", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 51, 'id_estado' => 4, 'municipio' => "Tovar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 52, 'id_estado' => 4, 'municipio' => "Urdaneta", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 53, 'id_estado' => 4, 'municipio' => "Zamora", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 54, 'id_estado' => 5, 'municipio' => "Alberto Arvelo Torrealba", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 55, 'id_estado' => 5, 'municipio' => "Andrés Eloy Blanco", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 56, 'id_estado' => 5, 'municipio' => "Antonio José de Sucre", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 57, 'id_estado' => 5, 'municipio' => "Arismendi", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 58, 'id_estado' => 5, 'municipio' => "Barinas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 59, 'id_estado' => 5, 'municipio' => "Bolívar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 60, 'id_estado' => 5, 'municipio' => "Cruz Paredes", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 61, 'id_estado' => 5, 'municipio' => "Ezequiel Zamora", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 62, 'id_estado' => 5, 'municipio' => "Obispos", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 63, 'id_estado' => 5, 'municipio' => "Pedraza", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 64, 'id_estado' => 5, 'municipio' => "Rojas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 65, 'id_estado' => 5, 'municipio' => "Sosa", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 66, 'id_estado' => 6, 'municipio' => "Caroní", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 67, 'id_estado' => 6, 'municipio' => "Cedeño", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 68, 'id_estado' => 6, 'municipio' => "El Callao", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 69, 'id_estado' => 6, 'municipio' => "Gran Sabana", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 70, 'id_estado' => 6, 'municipio' => "Heres", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 71, 'id_estado' => 6, 'municipio' => "Piar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 72, 'id_estado' => 6, 'municipio' => "Angostura (Raúl Leoni)", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 73, 'id_estado' => 6, 'municipio' => "Roscio", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 74, 'id_estado' => 6, 'municipio' => "Sifontes", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 75, 'id_estado' => 6, 'municipio' => "Sucre", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 76, 'id_estado' => 6, 'municipio' => "Padre Pedro Chien", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 77, 'id_estado' => 7, 'municipio' => "Bejuma", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 78, 'id_estado' => 7, 'municipio' => "Carlos Arvelo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 79, 'id_estado' => 7, 'municipio' => "Diego Ibarra", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 80, 'id_estado' => 7, 'municipio' => "Guacara", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 81, 'id_estado' => 7, 'municipio' => "Juan José Mora", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 82, 'id_estado' => 7, 'municipio' => "Libertador", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 83, 'id_estado' => 7, 'municipio' => "Los Guayos", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 84, 'id_estado' => 7, 'municipio' => "Miranda", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 85, 'id_estado' => 7, 'municipio' => "Montalbán", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 86, 'id_estado' => 7, 'municipio' => "Naguanagua", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 87, 'id_estado' => 7, 'municipio' => "Puerto Cabello", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 88, 'id_estado' => 7, 'municipio' => "San Diego", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 89, 'id_estado' => 7, 'municipio' => "San Joaquín", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 90, 'id_estado' => 7, 'municipio' => "Valencia", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 91, 'id_estado' => 8, 'municipio' => "Anzoátegui", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 92, 'id_estado' => 8, 'municipio' => "Tinaquillo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 93, 'id_estado' => 8, 'municipio' => "Girardot", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 94, 'id_estado' => 8, 'municipio' => "Lima Blanco", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 95, 'id_estado' => 8, 'municipio' => "Pao de San Juan Bautista", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 96, 'id_estado' => 8, 'municipio' => "Ricaurte", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 97, 'id_estado' => 8, 'municipio' => "Rómulo Gallegos", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 98, 'id_estado' => 8, 'municipio' => "San Carlos", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 99, 'id_estado' => 8, 'municipio' => "Tinaco", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 100, 'id_estado' => 9, 'municipio' => "Antonio Díaz", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 101, 'id_estado' => 9, 'municipio' => "Casacoima", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 102, 'id_estado' => 9, 'municipio' => "Pedernales", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 103, 'id_estado' => 9, 'municipio' => "Tucupita", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 104, 'id_estado' => 10, 'municipio' => "Acosta", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 105, 'id_estado' => 10, 'municipio' => "Bolívar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 106, 'id_estado' => 10, 'municipio' => "Buchivacoa", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 107, 'id_estado' => 10, 'municipio' => "Cacique Manaure", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 108, 'id_estado' => 10, 'municipio' => "Carirubana", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 109, 'id_estado' => 10, 'municipio' => "Colina", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 110, 'id_estado' => 10, 'municipio' => "Dabajuro", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 111, 'id_estado' => 10, 'municipio' => "Democracia", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 112, 'id_estado' => 10, 'municipio' => "Falcón", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 113, 'id_estado' => 10, 'municipio' => "Federación", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 114, 'id_estado' => 10, 'municipio' => "Jacura", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 115, 'id_estado' => 10, 'municipio' => "José Laurencio Silva", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 116, 'id_estado' => 10, 'municipio' => "Los Taques", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 117, 'id_estado' => 10, 'municipio' => "Mauroa", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 118, 'id_estado' => 10, 'municipio' => "Miranda", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 119, 'id_estado' => 10, 'municipio' => "Monseñor Iturriza", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 120, 'id_estado' => 10, 'municipio' => "Palmasola", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 121, 'id_estado' => 10, 'municipio' => "Petit", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 122, 'id_estado' => 10, 'municipio' => "Píritu", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 123, 'id_estado' => 10, 'municipio' => "San Francisco", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 124, 'id_estado' => 10, 'municipio' => "Sucre", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 125, 'id_estado' => 10, 'municipio' => "Tocópero", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 126, 'id_estado' => 10, 'municipio' => "Unión", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 127, 'id_estado' => 10, 'municipio' => "Urumaco", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 128, 'id_estado' => 10, 'municipio' => "Zamora", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 129, 'id_estado' => 11, 'municipio' => "Camaguán", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 130, 'id_estado' => 11, 'municipio' => "Chaguaramas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 131, 'id_estado' => 11, 'municipio' => "El Socorro", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 132, 'id_estado' => 11, 'municipio' => "José Félix Ribas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 133, 'id_estado' => 11, 'municipio' => "José Tadeo Monagas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 134, 'id_estado' => 11, 'municipio' => "Juan Germán Roscio", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 135, 'id_estado' => 11, 'municipio' => "Julián Mellado", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 136, 'id_estado' => 11, 'municipio' => "Las Mercedes", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 137, 'id_estado' => 11, 'municipio' => "Leonardo Infante", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 138, 'id_estado' => 11, 'municipio' => "Pedro Zaraza", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 139, 'id_estado' => 11, 'municipio' => "Ortíz", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 140, 'id_estado' => 11, 'municipio' => "San Gerónimo de Guayabal", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 141, 'id_estado' => 11, 'municipio' => "San José de Guaribe", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 142, 'id_estado' => 11, 'municipio' => "Santa María de Ipire", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 143, 'id_estado' => 11, 'municipio' => "Sebastián Francisco de Miranda", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 144, 'id_estado' => 12, 'municipio' => "Andrés Eloy Blanco", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 145, 'id_estado' => 12, 'municipio' => "Crespo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 146, 'id_estado' => 12, 'municipio' => "Iribarren", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 147, 'id_estado' => 12, 'municipio' => "Jiménez", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 148, 'id_estado' => 12, 'municipio' => "Morán", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 149, 'id_estado' => 12, 'municipio' => "Palavecino", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 150, 'id_estado' => 12, 'municipio' => "Simón Planas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 151, 'id_estado' => 12, 'municipio' => "Torres", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 152, 'id_estado' => 12, 'municipio' => "Urdaneta", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 179, 'id_estado' => 13, 'municipio' => "Alberto Adriani", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 180, 'id_estado' => 13, 'municipio' => "Andrés Bello", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 181, 'id_estado' => 13, 'municipio' => "Antonio Pinto Salinas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 182, 'id_estado' => 13, 'municipio' => "Aricagua", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 183, 'id_estado' => 13, 'municipio' => "Arzobispo Chacón", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 184, 'id_estado' => 13, 'municipio' => "Campo Elías", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 185, 'id_estado' => 13, 'municipio' => "Caracciolo Parra Olmedo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 186, 'id_estado' => 13, 'municipio' => "Cardenal Quintero", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 187, 'id_estado' => 13, 'municipio' => "Guaraque", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 188, 'id_estado' => 13, 'municipio' => "Julio César Salas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 189, 'id_estado' => 13, 'municipio' => "Justo Briceño", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 190, 'id_estado' => 13, 'municipio' => "Libertador", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 191, 'id_estado' => 13, 'municipio' => "Miranda", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 192, 'id_estado' => 13, 'municipio' => "Obispo Ramos de Lora", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 193, 'id_estado' => 13, 'municipio' => "Padre Noguera", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 194, 'id_estado' => 13, 'municipio' => "Pueblo Llano", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 195, 'id_estado' => 13, 'municipio' => "Rangel", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 196, 'id_estado' => 13, 'municipio' => "Rivas Dávila", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 197, 'id_estado' => 13, 'municipio' => "Santos Marquina", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 198, 'id_estado' => 13, 'municipio' => "Sucre", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 199, 'id_estado' => 13, 'municipio' => "Tovar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 200, 'id_estado' => 13, 'municipio' => "Tulio Febres Cordero", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 201, 'id_estado' => 13, 'municipio' => "Zea", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 223, 'id_estado' => 14, 'municipio' => "Acevedo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 224, 'id_estado' => 14, 'municipio' => "Andrés Bello", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 225, 'id_estado' => 14, 'municipio' => "Baruta", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 226, 'id_estado' => 14, 'municipio' => "Brión", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 227, 'id_estado' => 14, 'municipio' => "Buroz", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 228, 'id_estado' => 14, 'municipio' => "Carrizal", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 229, 'id_estado' => 14, 'municipio' => "Chacao", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 230, 'id_estado' => 14, 'municipio' => "Cristóbal Rojas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 231, 'id_estado' => 14, 'municipio' => "El Hatillo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 232, 'id_estado' => 14, 'municipio' => "Guaicaipuro", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 233, 'id_estado' => 14, 'municipio' => "Independencia", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 234, 'id_estado' => 14, 'municipio' => "Lander", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 235, 'id_estado' => 14, 'municipio' => "Los Salias", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 236, 'id_estado' => 14, 'municipio' => "Páez", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 237, 'id_estado' => 14, 'municipio' => "Paz Castillo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 238, 'id_estado' => 14, 'municipio' => "Pedro Gual", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 239, 'id_estado' => 14, 'municipio' => "Plaza", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 240, 'id_estado' => 14, 'municipio' => "Simón Bolívar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 241, 'id_estado' => 14, 'municipio' => "Sucre", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 242, 'id_estado' => 14, 'municipio' => "Urdaneta", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 243, 'id_estado' => 14, 'municipio' => "Zamora", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 258, 'id_estado' => 15, 'municipio' => "Acosta", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 259, 'id_estado' => 15, 'municipio' => "Aguasay", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 260, 'id_estado' => 15, 'municipio' => "Bolívar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 261, 'id_estado' => 15, 'municipio' => "Caripe", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 262, 'id_estado' => 15, 'municipio' => "Cedeño", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 263, 'id_estado' => 15, 'municipio' => "Ezequiel Zamora", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 264, 'id_estado' => 15, 'municipio' => "Libertador", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 265, 'id_estado' => 15, 'municipio' => "Maturín", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 266, 'id_estado' => 15, 'municipio' => "Piar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 267, 'id_estado' => 15, 'municipio' => "Punceres", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 268, 'id_estado' => 15, 'municipio' => "Santa Bárbara", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 269, 'id_estado' => 15, 'municipio' => "Sotillo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 270, 'id_estado' => 15, 'municipio' => "Uracoa", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 271, 'id_estado' => 16, 'municipio' => "Antolín del Campo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 272, 'id_estado' => 16, 'municipio' => "Arismendi", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 273, 'id_estado' => 16, 'municipio' => "García", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 274, 'id_estado' => 16, 'municipio' => "Gómez", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 275, 'id_estado' => 16, 'municipio' => "Maneiro", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 276, 'id_estado' => 16, 'municipio' => "Marcano", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 277, 'id_estado' => 16, 'municipio' => "Mariño", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 278, 'id_estado' => 16, 'municipio' => "Península de Macanao", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 279, 'id_estado' => 16, 'municipio' => "Tubores", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 280, 'id_estado' => 16, 'municipio' => "Villalba", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 281, 'id_estado' => 16, 'municipio' => "Díaz", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 282, 'id_estado' => 17, 'municipio' => "Agua Blanca", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 283, 'id_estado' => 17, 'municipio' => "Araure", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 284, 'id_estado' => 17, 'municipio' => "Esteller", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 285, 'id_estado' => 17, 'municipio' => "Guanare", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 286, 'id_estado' => 17, 'municipio' => "Guanarito", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 287, 'id_estado' => 17, 'municipio' => "Monseñor José Vicente de Unda", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 288, 'id_estado' => 17, 'municipio' => "Ospino", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 289, 'id_estado' => 17, 'municipio' => "Páez", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 290, 'id_estado' => 17, 'municipio' => "Papelón", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 291, 'id_estado' => 17, 'municipio' => "San Genaro de Boconoíto", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 292, 'id_estado' => 17, 'municipio' => "San Rafael de Onoto", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 293, 'id_estado' => 17, 'municipio' => "Santa Rosalía", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 294, 'id_estado' => 17, 'municipio' => "Sucre", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 295, 'id_estado' => 17, 'municipio' => "Turén", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 296, 'id_estado' => 18, 'municipio' => "Andrés Eloy Blanco", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 297, 'id_estado' => 18, 'municipio' => "Andrés Mata", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 298, 'id_estado' => 18, 'municipio' => "Arismendi", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 299, 'id_estado' => 18, 'municipio' => "Benítez", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 300, 'id_estado' => 18, 'municipio' => "Bermúdez", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 301, 'id_estado' => 18, 'municipio' => "Bolívar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 302, 'id_estado' => 18, 'municipio' => "Cajigal", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 303, 'id_estado' => 18, 'municipio' => "Cruz Salmerón Acosta", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 304, 'id_estado' => 18, 'municipio' => "Libertador", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 305, 'id_estado' => 18, 'municipio' => "Mariño", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 306, 'id_estado' => 18, 'municipio' => "Mejía", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 307, 'id_estado' => 18, 'municipio' => "Montes", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 308, 'id_estado' => 18, 'municipio' => "Ribero", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 309, 'id_estado' => 18, 'municipio' => "Sucre", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 310, 'id_estado' => 18, 'municipio' => "Valdéz", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 341, 'id_estado' => 19, 'municipio' => "Andrés Bello", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 342, 'id_estado' => 19, 'municipio' => "Antonio Rómulo Costa", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 343, 'id_estado' => 19, 'municipio' => "Ayacucho", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 344, 'id_estado' => 19, 'municipio' => "Bolívar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 345, 'id_estado' => 19, 'municipio' => "Cárdenas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 346, 'id_estado' => 19, 'municipio' => "Córdoba", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 347, 'id_estado' => 19, 'municipio' => "Fernández Feo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 348, 'id_estado' => 19, 'municipio' => "Francisco de Miranda", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 349, 'id_estado' => 19, 'municipio' => "García de Hevia", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 350, 'id_estado' => 19, 'municipio' => "Guásimos", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 351, 'id_estado' => 19, 'municipio' => "Independencia", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 352, 'id_estado' => 19, 'municipio' => "Jáuregui", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 353, 'id_estado' => 19, 'municipio' => "José María Vargas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 354, 'id_estado' => 19, 'municipio' => "Junín", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 355, 'id_estado' => 19, 'municipio' => "Libertad", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 356, 'id_estado' => 19, 'municipio' => "Libertador", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 357, 'id_estado' => 19, 'municipio' => "Lobatera", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 358, 'id_estado' => 19, 'municipio' => "Michelena", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 359, 'id_estado' => 19, 'municipio' => "Panamericano", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 360, 'id_estado' => 19, 'municipio' => "Pedro María Ureña", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 361, 'id_estado' => 19, 'municipio' => "Rafael Urdaneta", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 362, 'id_estado' => 19, 'municipio' => "Samuel Darío Maldonado", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 363, 'id_estado' => 19, 'municipio' => "San Cristóbal", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 364, 'id_estado' => 19, 'municipio' => "Seboruco", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 365, 'id_estado' => 19, 'municipio' => "Simón Rodríguez", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 366, 'id_estado' => 19, 'municipio' => "Sucre", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 367, 'id_estado' => 19, 'municipio' => "Torbes", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 368, 'id_estado' => 19, 'municipio' => "Uribante", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 369, 'id_estado' => 19, 'municipio' => "San Judas Tadeo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 370, 'id_estado' => 20, 'municipio' => "Andrés Bello", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 371, 'id_estado' => 20, 'municipio' => "Boconó", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 372, 'id_estado' => 20, 'municipio' => "Bolívar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 373, 'id_estado' => 20, 'municipio' => "Candelaria", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 374, 'id_estado' => 20, 'municipio' => "Carache", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 375, 'id_estado' => 20, 'municipio' => "Escuque", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 376, 'id_estado' => 20, 'municipio' => "José Felipe Márquez Cañizalez", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 377, 'id_estado' => 20, 'municipio' => "Juan Vicente Campos Elías", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 378, 'id_estado' => 20, 'municipio' => "La Ceiba", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 379, 'id_estado' => 20, 'municipio' => "Miranda", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 380, 'id_estado' => 20, 'municipio' => "Monte Carmelo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 381, 'id_estado' => 20, 'municipio' => "Motatán", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 382, 'id_estado' => 20, 'municipio' => "Pampán", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 383, 'id_estado' => 20, 'municipio' => "Pampanito", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 384, 'id_estado' => 20, 'municipio' => "Rafael Rangel", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 385, 'id_estado' => 20, 'municipio' => "San Rafael de Carvajal", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 386, 'id_estado' => 20, 'municipio' => "Sucre", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 387, 'id_estado' => 20, 'municipio' => "Trujillo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 388, 'id_estado' => 20, 'municipio' => "Urdaneta", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 389, 'id_estado' => 20, 'municipio' => "Valera", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 390, 'id_estado' => 21, 'municipio' => "Vargas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 391, 'id_estado' => 22, 'municipio' => "Arístides Bastidas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 392, 'id_estado' => 22, 'municipio' => "Bolívar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 407, 'id_estado' => 22, 'municipio' => "Bruzual", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 408, 'id_estado' => 22, 'municipio' => "Cocorote", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 409, 'id_estado' => 22, 'municipio' => "Independencia", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 410, 'id_estado' => 22, 'municipio' => "José Antonio Páez", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 411, 'id_estado' => 22, 'municipio' => "La Trinidad", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 412, 'id_estado' => 22, 'municipio' => "Manuel Monge", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 413, 'id_estado' => 22, 'municipio' => "Nirgua", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 414, 'id_estado' => 22, 'municipio' => "Peña", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 415, 'id_estado' => 22, 'municipio' => "San Felipe", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 416, 'id_estado' => 22, 'municipio' => "Sucre", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 417, 'id_estado' => 22, 'municipio' => "Urachiche", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 418, 'id_estado' => 22, 'municipio' => "José Joaquín Veroes", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 441, 'id_estado' => 23, 'municipio' => "Almirante Padilla", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 442, 'id_estado' => 23, 'municipio' => "Baralt", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 443, 'id_estado' => 23, 'municipio' => "Cabimas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 444, 'id_estado' => 23, 'municipio' => "Catatumbo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 445, 'id_estado' => 23, 'municipio' => "Colón", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 446, 'id_estado' => 23, 'municipio' => "Francisco Javier Pulgar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 447, 'id_estado' => 23, 'municipio' => "Páez", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 448, 'id_estado' => 23, 'municipio' => "Jesús Enrique Losada", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 449, 'id_estado' => 23, 'municipio' => "Jesús María Semprún", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 450, 'id_estado' => 23, 'municipio' => "La Cañada de Urdaneta", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 451, 'id_estado' => 23, 'municipio' => "Lagunillas", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 452, 'id_estado' => 23, 'municipio' => "Machiques de Perijá", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 453, 'id_estado' => 23, 'municipio' => "Mara", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 454, 'id_estado' => 23, 'municipio' => "Maracaibo", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 455, 'id_estado' => 23, 'municipio' => "Miranda", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 456, 'id_estado' => 23, 'municipio' => "Rosario de Perijá", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 457, 'id_estado' => 23, 'municipio' => "San Francisco", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 458, 'id_estado' => 23, 'municipio' => "Santa Rita", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 459, 'id_estado' => 23, 'municipio' => "Simón Bolívar", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 460, 'id_estado' => 23, 'municipio' => "Sucre", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 461, 'id_estado' => 23, 'municipio' => "Valmore Rodríguez", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()],
			['id' => 462, 'id_estado' => 24, 'municipio' => "Libertador", 'created_at' => DateTime::now(),'updated_at' => DateTime::now()]
        ];

        Municipio::insert($municipios); 	

    }

}
