<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProfesoresBDSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){

      $profesores = [
        ['cedula' => "04114310", 'nombres' => "SANCHEZ FONT, LUIS FERNANDO"],
        ['cedula' => "19411931", 'nombres' => "DIAZ PARRA, CESAR LUIS"],
        ['cedula' => "10855375", 'nombres' => "LOYO FIGUEROA, MARIA GRISELDA"],
        ['cedula' => "09838162", 'nombres' => "MUJICA GALLEGOS, JENETTE CRISCEIRA"],
        ['cedula' => "13096339", 'nombres' => "GRATEROL DERLYNG NOHEMI"],
        ['cedula' => "08510395", 'nombres' => "MOTA HERRERA, RAFAEL EDMUNDO"],
        ['cedula' => "11279074", 'nombres' => "OROPEZA NOGUERA, DENNAR COROMOTO"],
        ['cedula' => "12707944", 'nombres' => "HERNANDEZ CARRIZALEZ, ELGRE CECILIA"],
        ['cedula' => "19011575", 'nombres' => "MATOS PINEDA, LUIS FELIPE"],
        ['cedula' => "14211125", 'nombres' => "TOVAR AULAR, EDUARDO JOSÉ"],
        ['cedula' => "15769073", 'nombres' => "ALVAREZ GIMÉNEZ, ADRIANA THAIS"],
        ['cedula' => "10368605", 'nombres' => "SALAS GALIANO, YENNY ARACELIS"],
        ['cedula' => "07909929", 'nombres' => "MARTINEZ , RAUL OSWALDO"],
        ['cedula' => "14970865", 'nombres' => "NARIAS MUJICA, JOSE GREGORIO"],
        ['cedula' => "04475742", 'nombres' => "JIMENEZ EMAN, ISRAEL RAMON"],
        ['cedula' => "19414390", 'nombres' => "VALERA PERDOMO, WENDY YINETH"],
        ['cedula' => "12078183", 'nombres' => "CAMACHO PIÑA, MARIBEL CAROLINA"],
        ['cedula' => "07550860", 'nombres' => "MUÑOZ OJEDA, OSCAR MARTIN"],
        ['cedula' => "19614790", 'nombres' => "REYES CABRERA, JESUS GABRIEL"],
        ['cedula' => "19712775", 'nombres' => "DURAN REYES LORENZ CRISMAR"],
        ['cedula' => "12728914", 'nombres' => "VERA OCHOA, JULIO CESAR"],
        ['cedula' => "09252956", 'nombres' => "GUTIERREZ SIVIRA FRANK JOSE"],
        ['cedula' => "19639093", 'nombres' => "FIGUEROA VALERA, CESAR ANDRES"],
        ['cedula' => "17035812", 'nombres' => "HARO SUAREZ, SHARON ARON"],
        ['cedula' => "20617218", 'nombres' => "RUEDA RUEDA, JESUS ALBERTO"],
        ['cedula' => "06441923", 'nombres' => "BRICEÑO URBINA, ONEIDA DEL CARMEN"],
        ['cedula' => "11789375", 'nombres' => "AGUILAR YEPEZ, MIGUEL "],
        ['cedula' => "08519222", 'nombres' => "FERNANDEZ MEDINA, JORGE LUIS"],
        ['cedula' => "04478246", 'nombres' => "GONZALEZ DE HERNANDEZ, ELSY VIANELLY"],
        ['cedula' => "16594651", 'nombres' => "PEREZ FONSECA, GABRIEL ALEXANDER"],
        ['cedula' => "17468144", 'nombres' => "ALVARADO TIMAURE, NEYMAR DANIELA"],
        ['cedula' => "09267683", 'nombres' => "MONSALVE MORELBA, DEL PILAR"],
        ['cedula' => "10853020", 'nombres' => "CHACON VALENZUELA, FRANCISCO ALIRIO"],
        ['cedula' => "18053721", 'nombres' => "SILVA GRIMAN, NEURELYS MARIA"],
        ['cedula' => "15138673", 'nombres' => "MILIANI MEDINA, ANA DE LOS ANGELES"],
        ['cedula' => "07509786", 'nombres' => "REYES DE DURAN, LORENZA ANTONIA"],
        ['cedula' => "10860111", 'nombres' => "MARCHENA OROZCO, SERGIO ARGENIS"],
        ['cedula' => "09476559", 'nombres' => "PINO ELIZABETH, JOSEFINA"],
        ['cedula' => "07919899", 'nombres' => "GONZALEZ TOLEDO, JACKELINE "],
        ['cedula' => "08029360", 'nombres' => "OLIVO RUZA, DANIEL ALBERTO"],
        ['cedula' => "08516179", 'nombres' => "TORRES DE RUSSO, LILIAM COROMOTO"],
        ['cedula' => "12205462", 'nombres' => "MENDOZA GIL, WULLIAN RAMON"],
        ['cedula' => "19454356", 'nombres' => "HERNANDEZ TOVAR, JOSUE DAVID"],
        ['cedula' => "07374627", 'nombres' => "DUARTE , GUSTAVO "],
        ['cedula' => "16483518", 'nombres' => "RODRIGUEZ CORONADO, REMY ALEXANDER"],
        ['cedula' => "17870264", 'nombres' => "MARIN CARDOZO, JESUS MANUEL"],
        ['cedula' => "02607479", 'nombres' => "ANZOLA RODRIGUEZ, EDUARDO JOSÉ"],
        ['cedula' => "11275846", 'nombres' => "MIERES, ROSANA INES"],
        ['cedula' => "18054208", 'nombres' => "MILLA MENDOZA, MARYSABEL "],
        ['cedula' => "22330257", 'nombres' => "FLALLO MARC, EMMANUEL "],
        ['cedula' => "05536646", 'nombres' => "LIRA DE HERNANDEZ, AURA ESTELA"],
        ['cedula' => "14482241", 'nombres' => "JIMENEZ COELLO, HERMES RAUL"],
        ['cedula' => "15482101", 'nombres' => "TORREALBA YOVERA, GILDERSON JOSE"],
        ['cedula' => "16481950", 'nombres' => "CAMACHO MEDINA, YOFRAN JAVIER"],
        ['cedula' => "18547294", 'nombres' => "PERNACCHIO PERNALETE, ISIS MAIGREECE"],
        ['cedula' => "11272553", 'nombres' => "LEON LISCANO, LUIS EDGARDO"],
        ['cedula' => "19061959", 'nombres' => "HENRIQUEZ LUGO, MARIANELLA "],
        ['cedula' => "07553139", 'nombres' => "DELGADO SANTOS, ADOLFO JOSE"],
        ['cedula' => "15388141", 'nombres' => "ALVARADO BRACHO, FLOR MARIENIL"],
        ['cedula' => "11191930", 'nombres' => "BOVES PALENCIA, WILMA YELITZA"],
        ['cedula' => "17468264", 'nombres' => "SILVA TORRES, MARIA AUXILIADORA"],
        ['cedula' => "11654933", 'nombres' => "PEREZ , ROSA MARIA"],
        ['cedula' => "16950593", 'nombres' => "ORTIZ RODRIGUEZ, LEONARDO JOSE"],
        ['cedula' => "11648801", 'nombres' => "RIVERO TORRES, CARLOS JAVIER"],
        ['cedula' => "13986386", 'nombres' => "BARRETO LEDEZMA OSMANY RAFAEL"],
        ['cedula' => "04479742", 'nombres' => "MUÑOZ GUTIERREZ, RAFAEL"],
        ['cedula' => "16112241", 'nombres' => "PARRA CASTILLO, JOSE RAFAEL"],
        ['cedula' => "08513337", 'nombres' => "MONTILVA HERNANDEZ, MIGUEL ANGEL"],
        ['cedula' => "21302380", 'nombres' => "MORA MORA, JAVIER EDUARDO"],
        ['cedula' => "06960904", 'nombres' => "ARRIETTI GALARATTI, HUMBERTO "],
        ['cedula' => "12283450", 'nombres' => "MENDOZA MEDINA, MERYARIT OSCARINA"],
        ['cedula' => "19817890", 'nombres' => "CAÑIZALEZ SALCEDO, MAYERLING MILAGROS"],
        ['cedula' => "82000078", 'nombres' => "LOPEZ FENNER, ALEJANDRO ENRIQUE"],
        ['cedula' => "07444921", 'nombres' => "CASTILLO ACOSTA, MARCO ANTONIO"],
        ['cedula' => "06703976", 'nombres' => "RAMOS , JAVIER "],
        ['cedula' => "10717552", 'nombres' => "ALARCON , JORGE DOUGLAS"],
        ['cedula' => "18421483", 'nombres' => "FIGUEROA DAZA, DIANA ALEJANDRA"],
        ['cedula' => "04126304", 'nombres' => "ARRIETA PEREZ, EDUARDO EMIRO"],
        ['cedula' => "15767492", 'nombres' => "RIOS PARRA JOSE MANUEL"],
        ['cedula' => "15483035", 'nombres' => "PEÑA ORTEGA JESÚS RAFAEL"],
        ['cedula' => "32611447", 'nombres' => "CRUZ TELLERIA, ORESTES "],
        ['cedula' => "21127647", 'nombres' => "HIGUEREY LA, EFRAIN JOSE"],
        ['cedula' => "16904815", 'nombres' => "FIGUEROA DAZA, HAMLET ARMANDO"],
        ['cedula' => "12080586", 'nombres' => "APONTE SALCEDO, MANUEL ANTONIO"],
        ['cedula' => "12727799", 'nombres' => "MATUSALEN BARRIOS, JAIRO ANTONIO"],
        ['cedula' => "21623539", 'nombres' => "GOMEZ BLANCO, IDRIS MOISES"],
        ['cedula' => "09098966", 'nombres' => "GONZALEZ OSORIO, MONICA CRISTINA"],
        ['cedula' => "04682041", 'nombres' => "LUGO GARCIA, VICTOR JULIO"],
        ['cedula' => "13796953", 'nombres' => "GRATEROL HERNÁNDEZ, ENDER DAVID"],
        ['cedula' => "15768807", 'nombres' => "PERAZA CONEJERO, FELIX ENRIQUE"],
        ['cedula' => "16110444", 'nombres' => "ESCALONA DURANT, ALEJANDRA MODESTA"],
        ['cedula' => "12283410", 'nombres' => "YOVERA REYES MARIO JOSÉ"],
        ['cedula' => "07365810", 'nombres' => "CHIOSSONE RIOS JUANA INES"],
        ['cedula' => "07556087", 'nombres' => "MENDOZA FIGUEIRA, CARLOS ENRIQUE"],
        ['cedula' => "07923926", 'nombres' => "LOPEZ CAZORLA, ARGENIS JOEL"],
        ['cedula' => "04450157", 'nombres' => "GAZUI ROJAS, CARLOS ALBERTO"],
        ['cedula' => "04728743", 'nombres' => "MENDOZA FELIX, ALBERTO "],
        ['cedula' => "10861357", 'nombres' => "SAMPAYO LOPEZ, JOSE DE JESUS"],
        ['cedula' => "07397378", 'nombres' => "BARRIOS URBINA, ANA VICTORIA"],
        ['cedula' => "17806821", 'nombres' => "PIMENTEL VILLALOBOS, KIMBERLIN CAROL"],
        ['cedula' => "26325363", 'nombres' => "SERRANO CONTRERA, ANGELO JOSE"],
        ['cedula' => "20320398", 'nombres' => "MENDOZA GARAY, ANA CATALINA"],
        ['cedula' => "17867713", 'nombres' => "HERNANDEZ CASTELLANOS, BETZAIDY ISABEL"],
        ['cedula' => "03455919", 'nombres' => "MARTINEZ PERDOMO, AQUILES "],
        ['cedula' => "08515326", 'nombres' => "ECHETO BETANCOURT, ALEXIS JOSE"],
        ['cedula' => "13618203", 'nombres' => "CORDERO CASTILLO YAQUELIN ELADIA"],
        ['cedula' => "19903337", 'nombres' => "PEREZ ROJA, MANUEL "],
        ['cedula' => "16482816", 'nombres' => "ARENAS COLMENAREZ, ANA COROMOTO"],
        ['cedula' => "16111436", 'nombres' => "GUERRERO RODRIGUEZ, ROXANA DEL CARMEN"],
        ['cedula' => "12280544", 'nombres' => "PEÑA PIRELA, YAMINA MARGARITA"],
        ['cedula' => "09639991", 'nombres' => "CAMACARO GUEDEZ, JOSE MARIA"],
        ['cedula' => "24943143", 'nombres' => "SERRADA RODRIGUEZ, KATHEERINE CAROLINA"],
        ['cedula' => "07512773", 'nombres' => "RODRIGUEZ VALERO, LYLE ISABEL"],
        ['cedula' => "16417932", 'nombres' => "JIMENEZ RIVERO, JURE AMOAYI"],
        ['cedula' => "07913459", 'nombres' => "ROJAS AVENDAÑO, JUAN RAMON"],
        ['cedula' => "04478060", 'nombres' => "BARRETO MONTILLA, ORLANDO ANTONIO"],
        ['cedula' => "14798825", 'nombres' => "BARRETO GARCIA, JULIO CESAR"],
        ['cedula' => "12352979", 'nombres' => "ZERPA MARQUINA, LEOBARDO "],
        ['cedula' => "16868786", 'nombres' => "MANTO LOBO, MARIA ALEJANDRA"],
        ['cedula' => "20467390", 'nombres' => "RODRIGUEZ COROBO, ROBERT JESUS"],
        ['cedula' => "17612329", 'nombres' => "AZO PIÑA, MANUEL EDUARDO"],
        ['cedula' => "07355922", 'nombres' => "QUINTERO ESCALONA, GERARDO JOSE"],
        ['cedula' => "14211266", 'nombres' => "RICO CARMONA, HILDA ROCIO"],
        ['cedula' => "04856609", 'nombres' => "GONZALEZ DE NUÑEZ, MAIRA "],
        ['cedula' => "11425067", 'nombres' => "SALCEDO YANEZ, ALEXIS EDUARDO"],
        ['cedula' => "10370031", 'nombres' => "SILVA FERNANDEZ, ROSANNA DEL VALLE"],
        ['cedula' => "10860679", 'nombres' => "TOVAR , AMASILIS COROMOTO"],
        ['cedula' => "13864612", 'nombres' => "MEDINA MARTINEZ PEDRO JOSÉ"],
        ['cedula' => "22270781", 'nombres' => "TORREALBA OCHOA, JHOSELIS MILAGROS"],
        ['cedula' => "84497259", 'nombres' => "ESPINOSA APODACA, LUIS FELIPE"],
        ['cedula' => "18661994", 'nombres' => "GOMEZ OÑATE, LUZKARIN ELIZABETH"],
        ['cedula' => "13882191", 'nombres' => "LEON CALLES, IVAN JAVIER"],
        ['cedula' => "08793452", 'nombres' => "OCHOA JOSE LUIS"],
        ['cedula' => "13986226", 'nombres' => "LARA MATURET, FRANK MERY"],
        ['cedula' => "07583390", 'nombres' => "ARIAS , WILFREDO ANTONIO"],
        ['cedula' => "07323405", 'nombres' => "GIMENEZ ALVARADO, LUIS ALBERTO"],
        ['cedula' => "04480307", 'nombres' => "RIOS , WUILKAR MANOLO"],
        ['cedula' => "17993980", 'nombres' => "LEON CORDERO, REINALDO JOSE"],
        ['cedula' => "14608418", 'nombres' => "BRICEÑO FRANYER, JOSÉ "],
        ['cedula' => "10853892", 'nombres' => "RUIZ , PABLO "],
        ['cedula' => "06100670", 'nombres' => "ORTIZ DAVILA, GLADYS YAHAIRA"],
        ['cedula' => "03976314", 'nombres' => "LIRA DE PARRA, HILDA MAGALI"],
        ['cedula' => "09639135", 'nombres' => "ROJAS LOPEZ, OSWALDO AQUILES"],
        ['cedula' => "15283656", 'nombres' => "VALERA BARRADA JORGE ELIEZER"],
        ['cedula' => "05155788", 'nombres' => "PARES FREITES, PEDRO"],
        ['cedula' => "03235538", 'nombres' => "ZERPA CORREDOR, JESUS ARMANDO"],
        ['cedula' => "15782129", 'nombres' => "YBARRA ORTIZ, MARIA OLIMPIA"],
        ['cedula' => "16481291", 'nombres' => "RODRIGUEZ SEVILLA, HECTOR MIGUEL"],
        ['cedula' => "09623798", 'nombres' => "DELGADO PEROZO, VLADIMIR JOSE"],
        ['cedula' => "14608632", 'nombres' => "PALAO DURAN, MARIA DE LOS ANGELES"],
        ['cedula' => "19069109", 'nombres' => "SILVA VILLEGAS, LUIS ENRIQUE"],
        ['cedula' => "19817824", 'nombres' => "ZERPA GUEVARA, MARIANGELA FABIOLA"],
        ['cedula' => "10717661", 'nombres' => "RANGEL URBINA, YODILBEIDA "],
        ['cedula' => "14798013", 'nombres' => "CORTEZ SANCHEZ DANNIA ANGELICA"],
        ['cedula' => "19011602", 'nombres' => "CALZADA SALAZAR, GRISELDA CORIMAR"],
        ['cedula' => "19974216", 'nombres' => "PROAÑO TOVAR, HORTENCIA JOSE DEL CARMEN"],
        ['cedula' => "81543461", 'nombres' => "FONTANIVE ALIAGA, KENNETH ABSON"],
        ['cedula' => "09658275", 'nombres' => "HERNÁNDEZ MILLANO, ODRA ELENA"],
        ['cedula' => "09570319", 'nombres' => "CARUCI DE MARULLO, MARYS "],
        ['cedula' => "12280295", 'nombres' => "PINTO COLMENAREZ, MIRTHA "],
        ['cedula' => "14863593", 'nombres' => "QUINTERO HERNÁNDEZ, MARIA EFIGENIA"],
        ['cedula' => "17320035", 'nombres' => "GEORGE SANCHEZ, ARNAYS PASCUALA"],
        ['cedula' => "12726370", 'nombres' => "SIRA TORREALBA, CARMEN SUGELIN"],
        ['cedula' => "13612105", 'nombres' => "FERNANDEZ PARRA, JEANETTE CELESTE"],
        ['cedula' => "13985186", 'nombres' => "TORRES MEJIA, MARIA ALEJANDRA"],
        ['cedula' => "10849059", 'nombres' => "GONZALEZ LOPEZ ALBA DEL CARMEN"],
        ['cedula' => "15457141", 'nombres' => "MORENO VALERO, ORLANDO ANTONIO"],
        ['cedula' => "14918781", 'nombres' => "ZAVARCE ANDRADE, ANDREINA DAYANA CAROLINA"],
        ['cedula' => "07914620", 'nombres' => "FERNANDEZ SERRANO, GREGORIA MARIA"],
        ['cedula' => "04481094", 'nombres' => "PARRA PERDOMO, ELY ANTONIO"],
        ['cedula' => "04124935", 'nombres' => "GARRIDO CARDONA, JULIO BAGDAD"],
        ['cedula' => "10365166", 'nombres' => "GALLARDO , LUIS GREGORIO"],
        ['cedula' => "08036186", 'nombres' => "CONTRERAS DAVILA CARLOS"],
        ['cedula' => "07422743", 'nombres' => "MENDOZA HERNANDEZ, JULIO JORDAN"],
        ['cedula' => "05538754", 'nombres' => "RAMIREZ , LILIA ISABEL"],
        ['cedula' => "12728182", 'nombres' => "ZERPA CASTILLO, SUNAI "],
        ['cedula' => "16824738", 'nombres' => "LEON RIVERO, WILLIAN UZIEL"],
        ['cedula' => "15285910", 'nombres' => "RIVERO BUSTILLO, ANTONIO JOSÉ"],
        ['cedula' => "16822317", 'nombres' => "LOYO FERNANDEZ, DORAIMA DAYIRE"],
        ['cedula' => "15988403", 'nombres' => "PULIDO CHACON, MIRIAM ANGELIKA"],
        ['cedula' => "16822318", 'nombres' => "LOYO FERNANDEZ, DAMARYS DAYANA"],
        ['cedula' => "15767287", 'nombres' => "MUÑOZ GALEANO, RONY YULIANO"],
        ['cedula' => "12077931", 'nombres' => "MENDOZA ERIKA, YASMIN "],
        ['cedula' => "17378593", 'nombres' => "VILLAZANA LOPEZ, SAMUEL DAVID"],
        ['cedula' => "24394159", 'nombres' => "ROBLES CORDOBA JOSE RAMON"],
        ['cedula' => "03637206", 'nombres' => "ROSALES MEDINA, REINA MARTA"],
        ['cedula' => "11952273", 'nombres' => "DUGARTE ROJAS, RAYBETT "],
        ['cedula' => "10103498", 'nombres' => "LOBO SUESCUN, CARMEN NORA"],
        ['cedula' => "16594186", 'nombres' => "YOVERA YECERRA, JOSE LUIS"],
        ['cedula' => "11272927", 'nombres' => "LOYO TORTOLERO, FRANCISCO ANTONIO"],
        ['cedula' => "15768445", 'nombres' => "LINAREZ CASTILLO, ARYELIS YUDITH"],
        ['cedula' => "18646932", 'nombres' => "GUERRA CONTRERAS, YABEL ALBERTO"],
        ['cedula' => "12280422", 'nombres' => "ESCOBAR URICHE, DANNY JOSE"],
        ['cedula' => "07916459", 'nombres' => "LOYO TORTOLERO ELSY CRISTINA"],
        ['cedula' => "09602977", 'nombres' => "COLLANTES PINEDA, LIZMARY ELIZABETH"],
        ['cedula' => "09230864", 'nombres' => "ROMERO CORZO, JOSE ANTONIO"],
        ['cedula' => "11650165", 'nombres' => "GRATEROL GARRIDO, MAXIMILIAM "],
        ['cedula' => "16261144", 'nombres' => "ESCALONA RUIZ, MARIA VICTORIA"],
        ['cedula' => "19180462", 'nombres' => "AGUILAR ESCALONA, JOSEIDY ANDREINA"],
        ['cedula' => "18302868", 'nombres' => "LARROQUE , VICTOR ALFONSO"],
        ['cedula' => "10373843", 'nombres' => "LEON MARTINEZ, JUAN CARLOS"],
        ['cedula' => "21006296", 'nombres' => "PIRTO BEROES, RAFAEL JOSE"],
        ['cedula' => "13094725", 'nombres' => "PARRA RIVERO, EDUARDO JOSE"],
        ['cedula' => "10847750", 'nombres' => "CAMINO SANABRIA, JOSE MIGUEL"],
        ['cedula' => "15444035", 'nombres' => "PEREZ MARCHAN, FRANKLIN ANTONIO"],
        ['cedula' => "18054884", 'nombres' => "FREITEZ ALVARADO, JOSE ALEJANDRO"],
        ['cedula' => "10965887", 'nombres' => "CUENCA MEDINA, EDUARD JOSE"],
        ['cedula' => "10359537", 'nombres' => "SANTANA MONASTERIOS, OSCAR CIPRIANO"]
      ];

      DB::table('profesores_bd')->insert($profesores);

    }

}
